<%@ Page Language="C#" AutoEventWireup="true" Title="Games" MasterPageFile="~/Base.Master" CodeBehind="GameManagement.aspx.cs" Inherits="Tournament_Management.View.GameManagement" %>

<asp:Content ID="Content1" ContentPlaceHolderID="Games" runat="server">
    <div class="jumbotron">
        <span>
            <a runat="server" href="~/#">
                <img class="img-responsive"
                    src="../Static/Images/sport-news.png"
                    height="20"
                    style="display: block; margin-left: auto; margin-right: auto; margin-bottom: 25px; width: 20%;"
                    width="20" alt="home" />
            </a>
        </span>
        <h1 class="display-4">Tournament Management - Games</h1>
        <hr class="my-4">
        <p>Here you can manage the games for given tournament.</p>
    </div>
    <br />
    <br />
    <div class="panel panel-default">
        <div class="panel-heading">Games</div>
        <br />
        <div class="panel-body">
            <asp:GridView ID="tblGames"
                CssClass="table"
                runat="server"
                AllowPaging="true"
                PagerSettings-Mode="NextPrevious"
                PageSize="5"
                OnPageIndexChanging="tblTournament_PageIndexChanging"
                PagerSettings-PageButtonCount="2"
                DataKeyNames="id"
                OnRowUpdating="tblTournament_RowUpdating"
                OnRowCancelingEdit="tblTournament_RowCancelingEdit"
                OnRowDeleting="tblTournament_RowDeleting"
                AutoGenerateDeleteButton="true"
                AutoGenerateEditButton="true"
                OnRowEditing="tblTournament_RowEditing"
                AutoGenerateColumns="false">
                <Columns>
                    <asp:BoundField DataField="name"
                        ReadOnly="false"
                        HeaderText="Name" />
                    <asp:TemplateField HeaderText="Teams">
                        <ItemTemplate>
                            <asp:DropDownList ID="ddlist" DataSource='<%# Bind("Teams") %>' DataTextField="Name" DataValueField="Id" CssClass="form-control" runat="server">
                            </asp:DropDownList>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:Label ID="labelAdd" Text='Add tournaments below' runat="server">
                            </asp:Label>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Discipline">
                        <ItemTemplate>
                            <asp:Label ID="tourType" Text='<%# typeConverter(Eval("Type"))%>' runat="server">
                            </asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:DropDownList ID="tournamentTypes" DataSource='<%# Controller.TypeList %>' DataTextField="Value" DataValueField="Key" CssClass="form-control" runat="server">
                            </asp:DropDownList>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Active">
                        <ItemTemplate>
                            <asp:CheckBox ID="tourActive" runat="server" CssClass="form-check-input" Checked='<%# Eval("Active") %>' Enabled="false"></asp:CheckBox>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:CheckBox ID="tourActive" runat="server" CssClass="form-check-input" Checked='<%# Bind("Active") %>' Enabled="true"></asp:CheckBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Games">
                        <ItemTemplate>
                            <asp:Button runat="server" ID="gotoGames" CssClass="btn btn-light" Text="Games" OnCommand="gotoGames_Command" CommandArgument="" />
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <EditRowStyle CssClass="GridRowEditStyle" />
                <FooterStyle CssClass="GridViewFooterStyle" />
                <RowStyle CssClass="GridViewRowStyle" />
                <SelectedRowStyle CssClass="GridViewSelectedRowStyle" />
                <PagerStyle CssClass="GridViewPagerStyle" />
                <AlternatingRowStyle CssClass="GridViewAlternatingRowStyle" />
                <HeaderStyle CssClass="GridViewPagerStyle" />
            </asp:GridView>
            <div runat="server" id="editTourn" visible="true">
                <div class="row" id="addNewTournament" visible="true" runat="server">
                    <div class="panel-body">
                        <div class="h4">
                            Add new Tournament
                        </div>
                    </div>
                    <div class="col-md-6">
                        <asp:Label runat="server" AssociatedControlID="addNewT" Text="Discipline">
                        </asp:Label>
                        <asp:DropDownList runat="server" DataTextField="Value" DataValueField="Key" CssClass="form-control" DataSource='<%# Controller.TypeList %>' ID="addNewT">
                        </asp:DropDownList>
                    </div>
                    <div class="col-md-6">
                        <asp:Label runat="server" AssociatedControlID="nameT" Text="Name"></asp:Label>
                        <asp:TextBox runat="server" ID="nameT" CssClass="form-control"></asp:TextBox>
                        <br />
                        <asp:Button runat="server" ID="SaveNewT" CssClass="btn btn-secondary" Text="Add" OnCommand="SaveNewT_Command" />
                    </div>
                </div>
                <hr class="my-4">
                <div id="editMembersTournaments" runat="server" visible="false">
                    <div class="row">
                        <div class="col-md-5">
                            <asp:Label
                                runat="server"
                                AssociatedControlID="MembersFront"
                                Text="Members"></asp:Label>
                            <asp:ListBox
                                CssClass="form-control"
                                ID="MembersFront"
                                SelectionMode="Single"
                                DataSource='<%# Members %>'
                                runat="server"></asp:ListBox>
                        </div>
                        <div class="col-md-2">
                            <div class="btn-group" role="group">
                                <asp:Button ID="Button2" CssClass="btn btn-secondary" Text="<" OnClick="RemoveBtn_Click" runat="server" />
                                <asp:Button ID="Button3" CssClass="btn btn-secondary" Text=">" OnClick="AddBtn_Click" runat="server" />
                            </div>
                        </div>
                        <div class="col-md-5">
                            <asp:Label
                                runat="server"
                                AssociatedControlID="CandidatesFront"
                                Text="Candidates"></asp:Label>
                            <asp:ListBox
                                SelectionMode="Single"
                                CssClass="form-control"
                                ID="CandidatesFront"
                                DataSource='<%# Candidates %>'
                                runat="server"></asp:ListBox>
                        </div>
                    </div>
                    <br />
                    <div class="lead">To save your changes click update.</div>
                    <br />
                </div>
                <div id="exportButtons" runat="server">
                    <hr class="my-4">
                    <asp:Button ID="exportTeamXML" OnCommand="Export_CommandXML" CssClass="btn btn-secondary" Text='export XML' runat="server"></asp:Button>
                    <asp:Button ID="exportTeamJSON" OnCommand="Export_CommandJSON" CssClass="btn btn-secondary" Text='export JSON' runat="server"></asp:Button>
                </div>
            </div>
        </div>
        <br />
    </div>
    <%-- <div runat="server">
        <div class="container-fluid">
            <div id="rdbtnList1_container" runat="server">
                <p class="lead">Choose the Tournament</p>
                <br />
                <asp:DropDownList runat="server" CssClass="form-control" ID="tournamentList"></asp:DropDownList>
            </div>
            <asp:Button ID="btnShow" Text="Show Games" CssClass="btn btn-info my-auto" runat="server"></asp:Button>
        </div>
        <br />
        <br />
        <div class="panel panel-info">
            <div class="panel-heading">Games</div>
            <asp:Table Visible="false" ID="tblGames" CssClass="table" runat="server"></asp:Table>
        </div>
    </div>--%>
</asp:Content>