<%@ Page Language="C#" AutoEventWireup="true" Title="Games" MasterPageFile="~/Base.Master" CodeBehind="GameManagement.aspx.cs" Inherits="Tournament_Management.View.GameManagement" %>

<asp:Content ID="Content1" ContentPlaceHolderID="Games" runat="server">
    <div class="jumbotron">
        <span>
            <a runat="server" href="~/#">
                <img class="img-responsive"
                    src="../Static/Images/sport-news.png"
                    height="20"
                    style="display: block; margin-left: auto; margin-right: auto; margin-bottom: 25px; width: 20%;"
                    width="20" alt="home" />
            </a>
        </span>
        <h1 class="display-4">Tournament Management - Games</h1>
        <hr class="my-4">
        <p>Here you can manage the games for given tournament.</p>
    </div>
    <br />
    <asp:DropDownList runat="server" CssClass="form-control" DataSource='<%# Controller.Tournaments %>' DataTextField="Name" DataValueField="Id" ID="ddlTour"></asp:DropDownList>
    <br />
    <asp:Button runat="server" Text="OK" OnCommand="tourButton_Command" CssClass="btn btn-info" ID="tourButton"></asp:Button>
    <br />
    <br />
    <div class="panel panel-default">
        <div class="panel-heading">Games</div>
        <br />
        <div class="panel-body">
            <asp:GridView ID="tblGames"
                CssClass="table"
                runat="server"
                AllowPaging="true"
                PagerSettings-Mode="NextPrevious"
                PageSize="5"
                PagerSettings-PageButtonCount="2"
                DataKeyNames="id"
                OnRowUpdating="tblGames_RowUpdating"
                OnRowCancelingEdit="tblGames_RowCancelingEdit"
                OnRowDeleting="tblGames_RowDeleting"
                AutoGenerateDeleteButton="true"
                AutoGenerateEditButton="true"
                OnRowEditing="tblGames_RowEditing"
                AutoGenerateColumns="false">
                <Columns>
                    <asp:TemplateField HeaderText="Tournament">
                        <ItemTemplate>
                            <asp:Label runat="server" Text='<%# getTournamentsName(Eval("TournamentId")) %>' ID="textboxT1"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Team 1">
                        <ItemTemplate>
                            <asp:Label runat="server" Text='<%# getTeamsName(Eval("Scores[0].Team")) %>' ID="textboxT1"></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlistT1" DataSource='<%# Controller.Teams %>' DataTextField="Name" DataValueField="Id" CssClass="form-control" runat="server">
                            </asp:DropDownList>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Team 1 Points">
                        <ItemTemplate>
                            <asp:Label ID="labelT1" Text='<%# Eval("Scores[0].Points") %>' runat="server"></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox TextMode="Number" ID="textboxS1" runat="server" CssClass="form-control"></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Team 2">
                        <ItemTemplate>
                            <asp:Label runat="server" Text='<%# getTeamsName(Eval("Scores[1].Team")) %>' ID="textboxT2"></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlistT2" DataSource='<%# Controller.Teams %>' DataTextField="Name" DataValueField="Id" CssClass="form-control" runat="server">
                            </asp:DropDownList>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Team 2 Points">
                        <ItemTemplate>
                            <asp:Label ID="labelT2" Text='<%# Eval("Scores[1].Points") %>' runat="server"></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox TextMode="Number" ID="textboxS2" runat="server" CssClass="form-control"></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <EditRowStyle CssClass="GridRowEditStyle" />
                <FooterStyle CssClass="GridViewFooterStyle" />
                <RowStyle CssClass="GridViewRowStyle" />
                <SelectedRowStyle CssClass="GridViewSelectedRowStyle" />
                <PagerStyle CssClass="GridViewPagerStyle" />
                <AlternatingRowStyle CssClass="GridViewAlternatingRowStyle" />
                <HeaderStyle CssClass="GridViewPagerStyle" />
            </asp:GridView>
            <div runat="server" class="container" id="editTourn" visible="true">
                <div id="addNewGame" visible="true" runat="server">
                    <div class="h4">
                        Add new Game
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <asp:Label runat="server" AssociatedControlID="newGameTournDD" Text="Tournament">
                            </asp:Label>
                            <asp:DropDownList runat="server" DataSource='<%# Controller.Tournaments %>' DataTextField="Name" DataValueField="Id" CssClass="form-control" ID="newGameTournDD">
                            </asp:DropDownList>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <asp:Label runat="server" AssociatedControlID="addNewT1" Text="Team 1">
                            </asp:Label>
                            <asp:DropDownList runat="server" DataSource='<%# Controller.Teams %>'  DataTextField="Name" DataValueField="Id" CssClass="form-control" ID="addNewT1">
                            </asp:DropDownList>
                        </div>
                        <div class="col-md-2">
                            <div class="lead">
                                VS.
                            </div>
                        </div>
                        <div class="col-md-5">
                            <asp:Label runat="server" AssociatedControlID="addNewT2" Text="Team 2">
                            </asp:Label>
                            <asp:DropDownList runat="server" DataSource='<%# Controller.Teams %>'  DataTextField="Name" DataValueField="Id" CssClass="form-control" ID="addNewT2">
                            </asp:DropDownList>
                        </div>
                    </div>
                </div>
                <div class="row" id="addNewGamePoints" visible="true" runat="server">
                    <div class="col-md-5">
                        <asp:Label runat="server" AssociatedControlID="Score1" Text="Score"></asp:Label>
                        <asp:TextBox runat="server" ID="Score1" TextMode="Number" CssClass="form-control"></asp:TextBox>
                    </div>
                    <div class="col-md-2">
                        <div class="lead">
                            &nbsp;
                        </div>
                    </div>
                    <div class="col-md-5">
                        <asp:Label runat="server" AssociatedControlID="Score2" Text="Score"></asp:Label>
                        <asp:TextBox runat="server" ID="Score2" TextMode="Number" CssClass="form-control"></asp:TextBox>
                    </div>
                </div>
                <br />
                <asp:Button ID="btnAdd" OnCommand="btnAdd_SubmitUser" runat="server" Text="Save" CssClass="btn btn-info" />
                <div id="exportButtons" runat="server">
                    <hr class="my-4">
                    <asp:Button ID="exportTeamXML" OnCommand="Export_CommandXML" CssClass="btn btn-secondary" Text='export XML' runat="server"></asp:Button>
                    <asp:Button ID="exportTeamJSON" OnCommand="Export_CommandJSON" CssClass="btn btn-secondary" Text='export JSON' runat="server"></asp:Button>
                </div>
            </div>
        </div>
        <br />
    </div>
</asp:Content>