<%@ Page Language="C#" AutoEventWireup="true" Title="Team" MasterPageFile="~/Base.Master" CodeBehind="TeamManagement.aspx.cs" Inherits="Tournament_Management.View.TeamManagement" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TeamManagement" runat="server">
    <div class="jumbotron">
        <span>
            <a runat="server" href="~/#">
                <img class="img-responsive"
                    src="../Static/Images/baseball.png"
                    height="20"
                    style="display: block; margin-left: auto; margin-right: auto; margin-bottom: 25px; width: 20%;"
                    width="20" alt="people" />
            </a>
        </span>
        <h1 class="display-4">Team Management</h1>
        <p class="lead">Manage your favourite teams</p>
        <hr class="my-4">
        <p>...</p>
    </div>
    <div class="container-fluid">
    </div>
    <br />
    <br />
    <br />
    <div class="panel panel-default">
        <div class="panel-heading">Teams</div>
        <br />
        <div class="panel-body">
            <asp:GridView
                CssClass="table"
                runat="server"
                ID="teamGrid"
                AllowPaging="true"
                PagerSettings-Mode="NextPrevious"
                PageSize="5"
                OnPageIndexChanging="teamGrid_PageIndexChanging"
                PagerSettings-PageButtonCount="2"
                DataKeyNames="id"
                OnRowUpdating="teamGrid_RowUpdating"
                OnRowCancelingEdit="teamGrid_RowCancelingEdit"
                OnRowDeleting="teamGrid_RowDeleting"
                AutoGenerateDeleteButton="true"
                AutoGenerateEditButton="true"
                OnRowEditing="teamGrid_RowEditing"
                AutoGenerateColumns="false">
                <Columns>
                    <asp:BoundField DataField="name"
                        ReadOnly="false"
                        HeaderText="Name" />
                    <asp:TemplateField HeaderText="Members">
                        <ItemTemplate>
                            <asp:DropDownList ID="ddlist" DataSource='<%# Bind("List") %>' DataTextField="Name" DataValueField="Id" CssClass="form-control" runat="server">
                            </asp:DropDownList>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:Label ID="labelDD" Text='Add members below' runat="server">
                            </asp:Label>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Role">
                        <ItemTemplate>
                            <asp:Label ID="labelDD" Text='<%# typeConverter(Eval("Type"))%>' runat="server">
                            </asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlist" DataSource='<%# Controller.TypeList %>' DataTextField="Value" DataValueField="Key" CssClass="form-control" runat="server">
                            </asp:DropDownList>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Export">
                        <ItemTemplate>
                            <asp:Button ID="Export" ID="exportTeam" OnCommand="Export_Command" CssClass="form-control" Text='export' runat="server">
                            </asp:Button>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <EditRowStyle CssClass="GridRowEditStyle" />
                <FooterStyle CssClass="GridViewFooterStyle" />
                <RowStyle CssClass="GridViewRowStyle" />
                <SelectedRowStyle CssClass="GridViewSelectedRowStyle" />
                <PagerStyle CssClass="GridViewPagerStyle" />
                <AlternatingRowStyle CssClass="GridViewAlternatingRowStyle" />
                <HeaderStyle CssClass="GridViewPagerStyle" />
            </asp:GridView>
            <br />
            <div runat="server" id="editTeam" visible="true">
                <div class="h4">
                    Add new Team
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <asp:Label runat="server" AssociatedControlID="addNewT" Text="Discipline">
                        </asp:Label>
                        <asp:DropDownList runat="server" DataTextField="Value" DataValueField="Key" CssClass="form-control" DataSource='<%# Controller.TypeList %>' ID="addNewT">
                        </asp:DropDownList>
                    </div>
                    <div class="col-md-6">
                        <asp:Label runat="server" AssociatedControlID="nameT" Text="Name"></asp:Label>
                        <asp:TextBox runat="server" ID="nameT" CssClass="form-control"></asp:TextBox>
                        <br />
                        <asp:Button runat="server" ID="SaveNewT" CssClass="btn btn-secondary" Text="Add" OnCommand="SaveNewI_Command" />
                    </div>
                </div>
                <hr class="my-4">
                <div id="editMembersTeam" runat="server" visible="false">
                    <div class="row">
                        <div class="col-md-5">
                            <asp:Label
                                runat="server"
                                AssociatedControlID="MembersFront"
                                Text="Members"></asp:Label>
                            <asp:ListBox
                                CssClass="form-control"
                                ID="MembersFront"
                                SelectionMode="Single"
                                DataSource='<%# Members %>'
                                runat="server"></asp:ListBox>
                        </div>
                        <div class="col-md-2">
                            <div class="btn-group" role="group">
                                <asp:Button ID="Button2" CssClass="btn btn-secondary" Text="<" OnClick="RemoveBtn_Click" runat="server" />
                                <asp:Button ID="Button3" CssClass="btn btn-secondary" Text=">" OnClick="AddBtn_Click" runat="server" />
                            </div>
                        </div>
                        <div class="col-md-5">
                            <asp:Label
                                runat="server"
                                AssociatedControlID="CandidatesFront"
                                Text="Candidates"></asp:Label>
                            <asp:ListBox
                                SelectionMode="Single"
                                CssClass="form-control"
                                ID="CandidatesFront"
                                DataSource='<%# Candidates %>'
                                runat="server"></asp:ListBox>
                        </div>
                    </div>
                    <br />
                    <asp:Button ID="btnAdd" OnCommand="btnAdd_Submit" runat="server" Text="Save" CssClass="btn btn-info" />
                </div>
            </div>
        </div>
        <br />
    </div>
</asp:Content>
