<%@ Page Language="C#" Title="Users" MasterPageFile="~/Base.Master" AutoEventWireup="true" CodeBehind="UserManagement.aspx.cs" Inherits="Tournament_Management.View.UserManagement" %>

<asp:Content ID="Content1" ContentPlaceHolderID="Users" runat="server">
    <div class="jumbotron">
        <span>
            <a runat="server" href="#">
                <img class="img-responsive"
                    src="../Static/Images/users2.png"
                    height="20"
                    style="display: block; margin-left: auto; margin-right: auto; margin-bottom: 25px; width: 20%;"
                    width="20" alt="home" />
            </a>
        </span>
        <h1 class="display-4">User Management</h1>
        <p class="lead">Here you can add edit and delete users.</p>
        <hr class="my-4">
        <p></p>
        <br />
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Users</div>
        <div class="panel-body">
            <asp:GridView
                ID="tblUsers"
                CssClass="table"
                runat="server"
                DataKeyNames="id"
                OnRowUpdating="tblUsers_RowUpdating"
                OnRowCancelingEdit="tblUsers_RowCancelingEdit"
                OnRowDeleting="tblUsers_RowDeleting"
                AutoGenerateDeleteButton="true"
                AutoGenerateEditButton="true"
                OnRowEditing="tblUsers_RowEditing"
                OnRowDataBound="tblUsers_RowDataBound"
                AutoGenerateColumns="false">
                <Columns>
                    <asp:BoundField DataField="name"
                        ReadOnly="false"
                        HeaderText="Name" />
                    <asp:BoundField DataField="surname"
                        ReadOnly="false"
                        HeaderText="Surname" />
                    <asp:BoundField DataField="email"
                        ReadOnly="false"
                        HeaderText="Email" />
                    <asp:BoundField DataField="password"
                        ReadOnly="false"
                        NullDisplayText="hidden"
                        HeaderText="Password" />
                    <asp:BoundField DataField="role"
                        ReadOnly="false"
                        HeaderText="Role" />
                </Columns>
                <EditRowStyle CssClass="GridRowEditStyle" />
                <FooterStyle CssClass="GridViewFooterStyle" />
                <RowStyle CssClass="GridViewRowStyle" />
                <SelectedRowStyle CssClass="GridViewSelectedRowStyle" />
                <PagerStyle CssClass="GridViewPagerStyle" />
                <AlternatingRowStyle CssClass="GridViewAlternatingRowStyle" />
                <HeaderStyle CssClass="GridViewPagerStyle" />
            </asp:GridView>
        </div>
        <br />
    </div>
    </div>
</asp:Content>